### ISSUE TITLE
Wiki packaging is not Yarn compatible.

### ISSUE THREAD

**Issue by almereyda** [fedwiki/wiki#100]
This is probably an issue for very later, but as the Node.js ecosystem is moving over to the Yarn package manager (https://yarnpkg.com/), it may become of importance.

After running a Docker build on `node:6.10.0-alpine` (same as in https://github.com/fedwiki/wiki-server/issues/127) using Yarn, it has occured to me that the Wiki server cannot find its assets and replies to each request with `404`.

This does not happen when installed via `npm i -g wiki@0.10.3`.

**Comment by paul90** [comment]
Any problems you are having with yarn are best raised with them - see https://github.com/yarnpkg/yarn/issues

There are certainly problems with it working well with some parts of the Node.js ecosystem - for example I use `nvm` to manage multiple versions of node, and tying to install a packaged globally with yarn simply does not work as it does not install in the correct place.

**Comment by paul90** [comment]
It is worth adding that if installing locally, rather than globally, with `npm` you will need to install using `global-style`.

The root problem is that `yarn global add ...` does not give the same directory structure as `npm -g i ...`.
