### ISSUE TITLE
Story JSON standard

### ISSUE THREAD

**Issue by bryanph** [fedwiki/wiki#107]
I recently discovered federated wiki and I am quite impressed by the approach taken to journaling.
Since I am working on what seems like a very related project: https://github.com/bryanph/GeistMap, I was wondering whether there is some sort of standardization process around the Story JSON.

I did find this https://github.com/WardCunningham/Smallest-Federated-Wiki/wiki/Story-JSON but the last edit was from 2011. Is this still relevant?

**Comment by WardCunningham** [comment]
The core hasn't changed much but our documentation efforts have moved into wiki itself.

Here is a lineup that drills into your question starting from the stack.fed.wiki overview.
http://stack.fed.wiki/view/welcome-visitors/view/wiki-app-stack/view/top-down-overview/view/pages-of-plugins/view/json-schema

Here is a slightly older introduction for hackers that gets right to the point: recalling revisions.
http://dev.asia.wiki.org/view/welcome-visitors/view/hacking-federated-wiki/view/recall-revisions

You should join our wednesday hangout and tell us about your work.

**Comment by bryanph** [comment]
Thanks, that is very useful.
As for the hangout, would love to but I don't think I'll be able to make it today. I'll try to join frequently though in the future, I am quite excited about the work being done here. And perhaps I can contribute in some way in the future.
