### ISSUE TITLE
Login with google broken on subsites in fed.wiki.org

### ISSUE THREAD

**Issue by narath** [fedwiki/wiki#109]
Hi Martin, very intrigued by the idea of the federated wiki. I created a subsite http://medicine.fed.wiki.org to explore how this might be useful for sharing knowledge in medicine. When I click on the G button, I get the following error: Trouble starting OpenID, Did you enter a proper endpoint?

Was this not the appropriate way to setup a subsite?

**Comment by paul90** [comment]
Martin? I guess that is the person who directed you to one of Ward's old Federated Wiki farms. 

That particular wiki farm runs the old ruby version of the code - the OpenID authentication that it uses has been discontinued by many of the identity providers it originally used.

A more appropriate place, if you don't want to install the software, is to use the `tries.fed.wiki` farm. How about [narath.tries.fed.wiki](http://narath.tries.fed.wiki).

If you want to ask questions, or share your experiences, as you explore, there are a couple of places were we get together. We have a [matrix chat room](https://matrix.to/#/#fedwiki:matrix.org), and meetup online every Wednesday at 10am Portland local time, the link is announced by Ward on [twitter](https://twitter.com/WardCunningham), and recently also in the matrix room, about 15 minutes before hand.

**Comment by narath** [comment]
Thanks Paul. Very helpful. Yes, not sure where Martin came from (I must have been tired). 

Happy to install locally to try it out. If I have any challenges, will use the tries.fed.wiki

I'll try to checkin on the meetups.

Thanks, and keep up the good work.
