### ISSUE TITLE
Is my site visible in the federation? 

### ISSUE THREAD

**Issue by fmcpherson** [fedwiki/wiki#119]
I've built my own wiki server at https://fedwiki.frankmcpherson.net/view/welcome-visitors and I have been adding content on a regular basis. I am new to federated wiki and continue to learn, for example I know about the roster plugin and the ability using it to create a neighborhood, which enables me to discover new stuff that other people add to their wikis. (see https://fedwiki.frankmcpherson.net/view/welcome-visitors/view/testing) However, what I don't know is whether/how people are able to see my wiki and be able to take advantage of any of my content should they want to. Is it just up to serendipity or is there a place to register your site?

**Comment by WardCunningham** [comment]
I see that google has found your site.

![image](https://user-images.githubusercontent.com/12127/50974884-18ceb180-14a1-11e9-821d-a680e9733bf9.png)

But the search-scrape I run has not yet encountered your pages.

![image](https://user-images.githubusercontent.com/12127/50975082-8da1eb80-14a1-11e9-8f7b-21670ae1e772.png)

I'll look through your site and find something to fork. Then you are "in" the federation as I know it.
