### ISSUE TITLE
Installing Graphviz plugin

### ISSUE THREAD

**Issue by fmcpherson** [fedwiki/wiki#124]
I am trying to install the Graphviz plugin to my fedwiki server. I am attempting to install from the plugin on this page: https://fedwiki.frankmcpherson.net/view/welcome-visitors/view/site-index/view/more-about-algorithmic-markup 

When I attempt to install I get a message: service requires admin user
On the server side I see a "admin not defined for github"

I am using github as my oAuth provider, configured in config.json. 

All of the examples I have seen for setting up an admin user uses Google as the oAuth provider. Is it the case that admin user is only set up for Google and that to enable it I have to switch to Google? 

Is there another method for installing the Graphviz plugin? I have not been able to find any documentation.

**Comment by WardCunningham** [comment]
I have configured admin on servers using Google, Twitter and our own Friend security. I have not tried Github but I would be surprised if it didn't work. I examine status/owner.json of a claimed site to find out what key to use as the admin.

You can also install a plugin with npm. Install from the `node_modules/wiki` directory.

**Comment by fmcpherson** [comment]
I now have this working. The missing piece of info for me was getting the ID value from status/owner.json. The only doco I found about the admin user is here: http://admin.fedwiki.org/view/welcome-visitors/view/admin-user and it wasn't clear from that where to get the ID. I was getting it from the github_clientID in the config.json file.
