### ISSUE TITLE
Don't create ~/.wiki without asking first

### ISSUE THREAD

**Issue by chmac** [fedwiki/wiki#125]
I wanted to see how this works, a friend recommended it. I don't want it installed "globally" on my system. So I ran `mkdir wiki && cd wiki && yarn install wiki` then `npx wiki`. Now I realise that this wiki created `~/.wiki/` and started storing data there.

In my opinion, this is extremely unexpected for an NPM package I just installed as a dependency. I realise that y'all are most likely imagining folks use the `npm -g i wiki` as a means of installing a system wide application.

I figured I'd share my feedback as otherwise there's no way for the authors to know. I'm very interested in the concept of the federated wiki and keen to explore the software further. This decision to immediately create files in `~/.wiki` has, in my personal case, significantly reduced my trust in running this software on my machine. I wonder what other traces this software will leave on my computer without my knowledge. My next thought is that I need to install a VM or docker container in order to be able to run this on my machine. That is probably a barrier that's too high for me to get to.

Please feel free to ignore this issue if you're not interested. A friend has been evangelising the wiki and I really love the concept. I'm now very reluctant to run it, and I wanted to share that feedback as maybe this information might lead to helping federated wiki gain adoption. I imagine that honest, independent user feedback is usually hard to get.

As a closing thought, I'd love to have some method of testing the wiki listed on the README that doesn't require a system wide install. That or a test that tries to determine is `wiki` installed globally or locally, and switches the data directories / etc as a result.

End of feedback. :-)

**Comment by WardCunningham** [comment]
I'm sorry to have surprised you.

You can specify where wiki will retain state:
```
  --data, -d          location of flat file data 
```
You can learn of more wiki options:
```
  --help, -h          Show this help info and exit 
```
Knowing this, perhaps you can suggest what README wording would speak to you and not confuse others that just want a typical install.

**Comment by chmac** [comment]
@WardCunningham Sure thing, I do appreciate that y'all are making useful software and my reaction is a bit on the extreme side.

I'll fire a PR to update the README now.
