### ISSUE TITLE
missing CSS

### ISSUE THREAD

**Issue by fuck-capitalism** [fedwiki/wiki#135]
My page looks like this:

![image](https://user-images.githubusercontent.com/78769380/138167959-65d3b682-183e-4618-a7b3-3a26082d8a4e.png)

There are no edit controls or anything. What do I do?

**Comment by fuck-capitalism** [comment]
![image](https://user-images.githubusercontent.com/78769380/138187000-2338db07-9eb6-4058-b26d-d98746c331d7.png)
![image](https://user-images.githubusercontent.com/78769380/138187017-40d17b4d-4ca9-4e83-9af0-9c029ae331ae.png)

**Comment by fuck-capitalism** [comment]
> Could it be capitalism fighting back?

I hope so 😉

**Comment by WardCunningham** [comment]
Did you use npm to install wiki? Did it report errors while installing?
