### ISSUE TITLE
claiming wiki via persona doesn't seem to function

### ISSUE THREAD

**Issue by cmhobbs** [fedwiki/wiki#14]
When I log in with Persona with wiki's "Claim with your Email" button, I'm successfully verified by persona, wiki refreshes with my information, then wiki refreshes again with a modal stating:

```
Login Failure

It looks as if you are accessing the site using an alternative address.

Please check that you are using the correct address to access this site.
```

This is a private instance.

**Comment by garthk** [comment]
If you get this for `127.0.0.1`, try changing the URL in your browser to: `http://localhost:3000`
