### ISSUE TITLE
Automating releases, building and publication of package artefacts

### ISSUE THREAD

**Issue by almereyda** [fedwiki/wiki#142]
Hi! I have observed the Federated Wiki build toolchain is "missing" automated builds to NPM and the GitHub package repository or an OCI registry.

The current release processes depend on manual work by @paul90 in regular exchange with @WardCunningham. In times of Microsoft pleasing the world with GitHub Actions, we can choose to accept their offering and have it help us to automate releases "away", by reducing a few manual steps.

**Upstream**

This can benefit by a generalized workflow repository in the `fedwiki` organisation, from which manifests may be reused. It could carry this forge's brand in the `.github` repository, be an `actions` repository or carry any self-chosen name, maybe just here in `wiki` with a little overhead in a `.github` branded directory. Would there be opinions on this?

When there are no objections to the overall procedure, I would like to proceed with:

- [ ] `wiki-client` releases trigger package build and publication for NPM and OCI
- [ ] A new `wiki-client` release triggers the creation of a PR that offers to increase this dependency's version here.

---

- [ ] `wiki-server` releases trigger package build and publication for NPM and OCI
- [ ] A new `wiki-client` release triggers the creation of a PR that offers to increase this dependency's version here.

**Downstream**

Release automation for `wiki` is in place that

- [ ] builds and pushes the NPM package and multiarch OCI images upon release

Later we could reuse these preparations to have the plugin repositories behave in a similar way. Also self-updating draft releases, which aggregate recently merged PRs since last tag, can save a few clicks when doing bulk operations. In tying Wiki closer to GitHub, in return we receive some support to ease maintenance chores.

Paul and Ward, would the above seem useful to you?

**Comment by almereyda** [comment]
Initial work has been done to showcase automated releases and image builds for federated wiki using the GitHub infrastructure.

After the manifests of the @federated-wiki initiative were not updated since beginning of the pandemic, they were in a good spot to exemplify the suggested procedure. Were, because they now support (semi-)automatic builds.

A [`federated-wiki/workflows` repository](https://github.com/federated-wiki/workflows) holds the central [`build-and-push.yml` manifest](https://github.com/federated-wiki/workflows/blob/main/.github/workflows/build-and-push.yml), which is being reused in this example, which pushes only to GitHub Packages, due to ease of authentication, since no additional secrets are involved. An example for logging in and pushing to Docker Hub is contained in the comments of the file.

The [`federated-wiki/wiki-docker` repository](https://github.com/federated-wiki/wiki-docker) has been modified to run without a privileged user inside the container, and offers multiple ways to trigger a build:

Using the [detect and tag new version](https://github.com/federated-wiki/wiki-docker/actions/workflows/release-version.yml) ([manifest](https://github.com/federated-wiki/wiki-docker/blob/main/.github/workflows/release-version.yml)) workflow

- By merging a commit to `main` that increases the `WIKI_TAG` in the `Dockerfile`  
  In case the trigger evaluates positively, a tagged release is generated and a build by the CI workflow below is started
- https://github.com/federated-wiki/wiki-docker/pull/4
- [federated-wiki/wiki-docker#4 workflow run](https://github.com/federated-wiki/wiki-docker/actions/runs/6539176321)

Using the [CI workflow](https://github.com/federated-wiki/wiki-docker/actions/workflows/ci.yml)   ([manifest](https://github.com/federated-wiki/wiki-docker/blob/main/.github/workflows/ci.yml)) directly allows to create interim releases, which are additional to the upstream versions.

- By creating a new tagged release [on the GitHub releases page or via API](https://github.com/federated-wiki/wiki-docker/releases)
- By using the `workflow_dispatch` event trigger
  ![image](https://github.com/fedwiki/wiki/assets/1645308/954ba736-613b-40da-a892-1ddeca12dcb9)

This way it is easy to automatically track upstream wiki versions, and to offer pull requests that increase the package version, while allowing to create manual interim releases for different purposes, mainly patch and test releases.

The [`federated-wiki/wiki-docker-plugins` repository](https://github.com/federated-wiki/wiki-docker-plugins), which is used for assembling a wiki distribution, adopts [a simpler CI workflow](https://github.com/federated-wiki/wiki-docker-plugins/actions/workflows/ci.yml) ([manifest](https://github.com/federated-wiki/wiki-docker-plugins/blob/main/.github/workflows/ci.yml)) than the previous version, and basically only contains triggers and build configuration. The Containerfile has as well been adapted to work without root inside the container.

The artefacts are uploaded to [the Packages repository of the GitHub organisation, here `federated wiki`](https://github.com/orgs/federated-wiki/packages).

- [`ghcr.io/federated-wiki/base`](https://github.com/federated-wiki/wiki-docker/pkgs/container/base)
- [`ghcr.io/federated-wiki/distribution`](https://github.com/federated-wiki/wiki-docker-plugins/pkgs/container/distribution)

Due to suggested snippets in the Docker, Node.js and GitHub documentation, the build is performed for both the `amd64` and `arm64` (`aarch64`) architectures, and packages for both are made available via the same image names and tags.

Now it will be much easier and much more deterministic to create new versions of our federated wiki distribution for the local use cases, mainly the `federated.wiki` and `commoning.wiki` farms.

**Comment by paul90** [comment]
I see little benefit in adding a script that will be doing little more  than simply automate `npm publish`. That is just adding something extra that is likely to go wrong, and would need maintaining.

I think for your upstream workflows, you are asking us to increment the wiki version when changes to any of the included wiki parts is updated. I don't see a problem with remembering to do that.

Not sure how your automation copes when we package either wiki or any of its parts with a dist-tag `next`, so that major changes can be tested. Hopefully the automation will simply ignore anything other than the `latest` tag.

**Comment by almereyda** [comment]
Thanks for looking at this. Indeed my automation only picks up from what is published to these repositories, basically the Dockerfiles there, and has no integration whatsoever with the wiki upstream here or on NPM, yet.

Marking releases as tags and pushing them here, eventually also using the GitHub releases feature on them, will only make it easier for third-parties to follow what's going on in Wiki land, and is not needed for the procedures above.

I'd still consider NPM being the canonical source for Wiki releases, which could be polled by a daily job for changes, avoiding any tight integration, e.g. with Webhooks.

Building always up-to-date images from `next` would be another question.

What's left then is to increase wiki versions, when one of its downstream packages change their version, too, yes. The automation could pick this up with regular polling, as mentioned above.

**Comment by almereyda** [comment]
I have now set up a clunky extension of the previous example, which will query NPM once a day for new wiki versions, in comparison to the one available there, and build a new container from it, when necessary:

* [Pull and compare last NPM release · Workflow runs · federated-wiki/wiki-docker](https://github.com/federated-wiki/wiki-docker/actions/workflows/pull-and-compare-last-npm-release.yml)

This has been exemplified in this task run:

* [Pull and compare last NPM release · federated-wiki/wiki-docker@ab0e708](https://github.com/federated-wiki/wiki-docker/actions/runs/6789571398/job/18457081355)

It remains left to increase the base image version of the dependant distribution, once a new base image has been released.

Now I also understand your remark regarding a mutable `dist` version tag on NPM better.

The script queries NPM at https://github.com/federated-wiki/wiki-docker/blob/7338dd107af2a539ce066c0d9d28a89c9c3099fe/.github/workflows/pull-and-compare-last-npm-release.yml#L36 with:

    curl -sL https://registry.npmjs.org/wiki/latest | jq -r .version

Whenever this is different to the previous version in the Dockerfile https://github.com/federated-wiki/wiki-docker/blob/7338dd107af2a539ce066c0d9d28a89c9c3099fe/.github/workflows/pull-and-compare-last-npm-release.yml#L41, it is used for our next release:

    ${{ steps.dockerfile.outputs.version != steps.npm.outputs.version }}

There appear to be many ways in which this can break. For getting this right, I had often to revert version increase commits, because the triggers were not working as expected. But the one that checks for new versions, which will also try to generate a new, assumingly existing release, from a downgraded version, but fail sufficiently due to the preexisting tag:

* [Merge pull request #27 from federated-wiki/revert-25-0.32.1 · federated-wiki/wiki-docker@ab0e708](https://github.com/federated-wiki/wiki-docker/actions/runs/6789536987/job/18456957559)

Let's see if that schedule actually works, and if it manages to react to new releases on its own now.

**Comment by almereyda** [comment]
There are now automated releases for the packaged distribution of wiki. I can go to

* [Increase base version · Workflow runs · federated-wiki/wiki-docker-plugins](https://github.com/federated-wiki/wiki-docker-plugins/actions/workflows/increase-base-version.yml)

enter the old and the new version number, and will end up with new tagged releases for the distribution, both for the git tag and the OCI image tag.

* [Releases · federated-wiki/wiki-docker-plugins](https://github.com/federated-wiki/wiki-docker-plugins/releases)
* [Package distribution](https://github.com/federated-wiki/wiki-docker-plugins/pkgs/container/distribution)

There is still room for improvement. For example building from the implicit `latest` tag before did not provide much customisability, but would make sure we are always up to date when cutting a release artifact.

There are other ways to update container images when their base images changes, but for now I like the explicitness of syncing the version tag to the wiki upstream of the distribution.

**Comment by almereyda** [comment]
I liked what you said in https://github.com/fedwiki/wiki/pull/143#issuecomment-1814957885

> Deployment specific stuff, be it docker, nix, or something else, really don't belong in the repo for the npm package. Much better that it is elsewhere in a repo with those who use it, and can maintain it.

Which totally makes sense, given that it works.

**Comment by almereyda** [comment]
Just confirming that this works now as intended.

The last release for

- https://github.com/fedwiki/wiki-security-passportjs/issues/41#issuecomment-1824761727

appeared in the morning at

- https://github.com/federated-wiki/wiki-oci-base/releases/tag/v0.33.0

which allowed me to manually initiate the upgrade with

- https://github.com/federated-wiki/wiki-oci-distribution/actions/runs/6983413609

and a new container was born:

- https://github.com/federated-wiki/wiki-oci-distribution/pkgs/container/distribution

Now that I have learned about the `repository_dispatch` event, there is also an implementation path for automating the build cycle of the distribution.
