### ISSUE TITLE
Plug-ins (default set)

### ISSUE THREAD

**Issue by paul90** [fedwiki/wiki#31]
While we are adding the Markdown plug-in, #28, are there any of the older plug-ins that should be removed from the default install?

My initial though is that there are a few that rely on specific server attached hardware, twadio and txtzyme. And probably logwatch and parse as well.

Thoughts...

**Comment by WardCunningham** [comment]
I have been working towards this reorganization as a goal with the working title [Plugin Catalog](http://goals.pods.wiki.org/view/welcome-visitors/view/top-maintenance-priorities/ward.asia.wiki.org/plugin-catalog). I would like to push this towards a conclusion, no matter how modest. I invite closing comments here.
