### ISSUE TITLE
warnings when `npm install` of this package with io.js

### ISSUE THREAD

**Issue by pmuellr** [fedwiki/wiki#43]
Here's what happened when I did an `npm install` that included wiki: 0.6.x in the deps:

    npm WARN engine wiki@0.6.3: wanted: {"node":"0.10"} (current: {"node":"1.6.2","npm":"2.7.1"})

repeated 42 more times for: 
wiki-plugin-data wiki-plugin-markdown wiki-plugin-factory wiki-plugin-favicon
wiki-server wiki-plugin-activity wiki-plugin-future wiki-plugin-changes
wiki-plugin-html wiki-plugin-line wiki-plugin-logwatch wiki-plugin-audio
wiki-plugin-chart wiki-plugin-calculator wiki-plugin-calendar
wiki-plugin-federatedwiki wiki-plugin-mathjax wiki-plugin-parse
wiki-plugin-efficiency wiki-plugin-bytebeat wiki-plugin-report
wiki-plugin-flagmatic wiki-plugin-reduce wiki-plugin-metabolism
wiki-plugin-txtzyme wiki-plugin-reference wiki-plugin-force wiki-plugin-bars
wiki-plugin-pushpin wiki-plugin-code wiki-plugin-scatter wiki-plugin-radar
wiki-plugin-paragraph wiki-plugin-image wiki-plugin-twadio wiki-plugin-map
wiki-plugin-grep wiki-plugin-linkmap wiki-plugin-method wiki-plugin-roster
wiki-plugin-pagefold wiki-plugin-rollup wiki-plugin-video

**Comment by paul90** [comment]
Have just released of wiki: 0.7.0 as well as updating the package file for each of the plugins. 

Those warning message should no longer appear.
