### ISSUE TITLE
Copying/forking multiple pages (i.e. complete wikis)

### ISSUE THREAD

**Issue by coevolving** [fedwiki/wiki#50]
If I get to the state where there are a significant number of wiki pages to be compared and merged together, asking a collaborator to fork one page at a time will get to be annoying.  As an example, there could be a complete wiki site for a pattern language, and forking each one independently could be tedious.

In looking at Tiddlywiki v5 (which uses node.js), I can see that it would be relatively straightforward for someone to copy a directory of Tiddlers (which are now separate files, rather than one huge file).  This means that migrating a whole wiki site is relatively straighttforward.

On some previous communications, I think that @WardCunningham had said that he maintains a private wiki site on machine behind a firewall, and then pushes content out to public sites.  Is this done by forking every private page into a public page, or is there some batch copying that is done?

**Comment by interstar** [comment]
Each page is just an ordinary file. I edit my SFW locally (on my laptop) and use rsync to push changes to a publicly visible server.

There are a couple of downsides to this. Sometimes I accidently try to edit on the live server and these changes get lost. And there's no useful synchronization magic possible between my public and private server. My public wiki doesn't KNOW that the pages came from my private wiki. It suppose it assumes it created them.

However it works perfectly well. And right now it's the best solution for me.

**Comment by WardCunningham** [comment]
I publish one site using rsync. I defeat login even for myself on the public site. This way I am bluntly reminded should I try to edit the wrong copy.

http://code.fed.wiki.org/exploring-federated-wiki.html

My more frequent technique is to edit pages on a local server when I'm not sure they should be published. When I do decide to publish, I start logged into the public server and then drag and fork the page from my local server to publish. This works for one or two pages, maybe more when they are nicely linked.

**Comment by WardCunningham** [comment]
The wiki client could detect when there are two servers that should be sync'd, maybe marked as such by having the identical flag. It could fetch sitemaps for each and then quietly move newer pages over older pages unless they have conflicting changes. Conflicts would show in Recent Changes because the two flags would not merge. 

http://forage.ward.fed.wiki.org/more-about-activity-plugin.html

The current side-by-side manual merge is already supported as is bulk merge by dragging journals atop one another. This hasn't been coded yet because it is not known to be a good idea and in demand.

**Comment by coevolving** [comment]
@interstar Thanks for the rsync method.

@WardCunningham, the instructions at http://code.fed.wiki.org/exploring-federated-wiki.html are helpful.

I'm thinking of ways that I could make one wiki of a farm easier for someone to replicate.  I recognize that each wiki page is just a file, and could be copied manually rather than dragging-and-forking.  What then happens to links from one page to another page locally?  If I copied a snapshot of all a directory of wiki pages up to Github so that other people could download them, would that preserve the links between the local pages?

Or is there another suggestion of the way to export a whole wiki?

**Comment by WardCunningham** [comment]
The node server has /system/export.json which will export a whole site.

Try exporting the entire glossary site:
http://glossary.asia.wiki.org/system/export.json

We've only ever used ad-hoc scripts to load an exported site anywhere else. Perhaps if one dropped an export.json file on an empty site it would just load it.

**Comment by coevolving** [comment]
@WardCunningham Is the export.json a normal part of the federated wiki, or an installable plug-in?

When I try http://fed.coevolving.com/system/export.json , I get:
Cannot GET /system/export.json

**Comment by paul90** [comment]
The ability to do an export was added at the end of 2014.

When I moved from my single site on OpenShift to running a personal wiki farm I copied the files, and reorganized them locally, before copying them to the new farm. I ran a local farm while doing this so I could check I was getting it organized the way I wanted.

**Comment by coevolving** [comment]
@paul90 Ah, I must be downlevel on my Openshift site.  I guess I'm going to have to update that.

**Comment by almereyda** [comment]
Additionally to mere rsync'ing directories, I prefer to have a fedwiki flat
file data directory backed up by a git repository, so I can easily push and
pull it from and to remote (private) repositories.
Then the only addition when merging between remote and local branches is
by-hand edits of the stored (originating) FQDN of a page sometimes.

**Comment by WardCunningham** [comment]
> We've only ever used ad-hoc scripts to load an exported site anywhere else. Perhaps if one dropped an export.json file on an empty site it would just load it.

I've started working on this.

**Comment by WardCunningham** [comment]
Since wiki-client 0.4.14 published on June 15th one has been able to drop an export file on a site and then click to add desired pages on a new site. The bulk of the code went in with this commit: https://github.com/fedwiki/wiki-client/commit/db5eadea99188aaa540ac1803e1edcf43e9582ab
