### ISSUE TITLE
Pages with Unicode Titles Don't Work

### ISSUE THREAD

**Issue by polm** [fedwiki/wiki#54]
I ran the wiki on my machine and noticed that pages with (for example) Japanese-only titles don't work. However, if the title includes some ASCII it will work. So "テスト" results in a page I can't edit, but "テストfiddle" results in an editable page, but only "fiddle" shows in links. Is this a bug?

**Comment by WardCunningham** [comment]
This is a known limitation that goes back to the earliest days of the project when we were unsure anyone would ever use the program at all. We have designed mechanisms that could relieve us of these limitations but have only experimental implementations. See https://github.com/fedwiki/wiki-client/pull/103

We would love to work with strong developers who are familiar with and motivated to develop sound alternatives to our current safe key (slug) generation mechanisms.

**Comment by polm** [comment]
Oh, thanks for the pointer to the main issue - I'll have a look over there.

**Comment by WardCunningham** [comment]
With no further activity I now close this issue.
