### ISSUE TITLE
Rename this repo to "wiki" to match npm package "wiki"

### ISSUE THREAD

**Issue by WardCunningham** [fedwiki/wiki#55]
This repo dates back to a period of flux when the ruby implementation was still the "reference" implementation. However, the ruby version has fallen into disrepair. This repo is now our reference and should be easily cloned and managed by server operators who which to keep a variation on their sites but still want to track this repo as their upstream.

All this will be a lot simpler for everyone if this repo were renamed "wiki".

GitHub documentation says this will be easy. 
https://help.github.com/articles/renaming-a-repository/

We have 30 forks already. Folks, what do you think? Better if this is "wiki"? Comments here could explain what followers might do with their existing forks. GitHub says that even this is not required but preferable. We are trying to simplify after all.

We would also like to see forks of this repo flourish as scoped packages easily installed by anyone from npm. Npm docs say even this is easy.
https://docs.npmjs.com/getting-started/scoped-packages

Comments are welcome as to whether there are other cleanup activities which should be conducted here before making this change. I'm interested specifically in normalizing how we handle independent plugins. Can we think about a name change in about a week?

**Comment by paul90** [comment]
Think this would be a very good idea - as would renaming "wiki-node-server" to "wiki-server".

Behind the scenes github will forward from the current names to the new names, both on the website and for git remotes. I would not expect the current names of those two repositories to be reused, other than changing the names back in the event of some other implementation becoming the reference one.

**Comment by WardCunningham** [comment]
Let's do it. Maybe this week?

GitHub's [Rename Help](https://help.github.com/articles/renaming-a-repository/) adds: However, to reduce confusion, we strongly recommend updating any existing local clones to point to the new repository URL. You can do this by using git remote on the command line:
```
git remote set-url origin new_url
```

Presumably those maintaining forks in GitHub would eventually rename their repos too.

**Comment by WardCunningham** [comment]
Both of these pull requests look good. I'm guessing this will take three steps which can be applied in any order. Perhaps this morning would be a good time to do this then we can look around for downstream problems and discuss them in our hangout.

* [ ] merge to master
* [ ] rename the repo
* [ ] publish to npm

**Comment by paul90** [comment]
The renaming is now complete.

**Comment by WardCunningham** [comment]
Sweet. Thank you.
