### ISSUE TITLE
Can I run my wiki at http://my.server.com/wiki ?

### ISSUE THREAD

**Issue by khinsen** [fedwiki/wiki#60]
I am trying to set up a wiki server on a server that already has a Web site running at `http://my.server.com/`. The easiest workaround is to use another port than 80 or 443, but then I can't use my own wiki because I live behind a firewall that blocks almost all ports.

A solution that I have been exploring is to use `http://my.server.com/wiki` as the root URL, using the `ProxyPass` feature of Apache (which is running the main Web server). This fails because wiki uses absolute URLs for everything. Can this be configured somehow?

**Comment by nrn** [comment]
The wiki is really set up to be used on it's own subdomain. The federation bases identity on domain name, and expects to be able to find the endpoints needed to participate in the federation at the same path on everyones server.

The good news is you can use apache up as a reverse proxy, letting you setup many virtualhosts on the same machine. Just add a dns record pointing another subdomain (wiki.my.server.com, wiki.server.com, etc.) at the same server, then instruct apache to route all that traffic through to the wiki running on a different port, something like https://www.digitalocean.com/community/tutorials/how-to-use-apache-http-server-as-reverse-proxy-using-mod_proxy-extension

Let us know if this works for your situation, and how it goes!

**Comment by khinsen** [comment]
I don't own the domain of my server, so I cannot modify DNS records. The domain is owned by my employer, a rather big organization. I could ask them to create a DNS record for me, but that's a year's worth of paperwork.

If the domain name defines a site's identify, this effectively means that setting up a wiki site requires being a Web Wizard. Ordinary mortals will have to wait for service providers offering wiki hosting. But service providers will appear only once there is a clear demand, which in turn means a sufficient visibility of the federation.

This makes me wonder if Federated Wiki is a research project that isn't meant to grow, or a new medium aiming at widespread adoption. In the latter case, what's the plan for getting over the initial adoption barrier?

**Comment by WardCunningham** [comment]
@khinsen, There is widespread learned helplessness among internet users and especially employees. If opposing this is not a battle that interests you then you may be better served with quip or slack. But be warned, these things blow through companies like the wind.

No, we are not a research project. This is not an experiment that will end. We build on well established and lasting technologies while remaining careful to keep our most precious work, the documents we write, in a form that is both simple and unversioned. And we make sure no special permissions are required to keep them.

I can tell that we have made some decision that inconveniences you. For this I am sorry. But we are working towards a goal that is bigger than, as they say in the valley, the next dead unicorn.

**Comment by khinsen** [comment]
@WardCunningham Thanks for your comments - I actually I agree with pretty much all of that, and I am very interested to get away from proprietary tools such as Quip or Slack and return to computer users the full control over their contents.

The original issue that I asked about is, as you say, an inconvenience, no more. I know what I need to do to fix it (basically get my own domain), and it would take me about half a day to do so. That's OK for working with technology on the bleeding edge.

What worries me is that one site = one domain seems to be not just an implementation detail, but a design principle of Federated Wiki, if I understood @nrn correctly. The whole point of being part of a federation is to have neighbors with overlapping interests. I want to run a site about computational science, which thus makes sense only if can expect other computational scientists to do the same. Everyone in that community has decent computer skills by definition. Most people can handle complex software installations, and have some programming experience. Everyone has a personal Web space, many run dedicated servers. But I can come up with only two names of people who run their own domain and know how to deal with DNS.

At the institutional level, there is a similar gap between setting up a Web service and requesting a domain name. For a Web service, all it takes is a phone call, but getting a site-specific DNS record looks like a long bureaucratic fight (I haven't tried yet). As a scientist, my credibility is partly related to my affiliation, so I would really prefer to run a wiki site on computational science under the flag of my employer. And my employer would happily let me do that as long as it happens within my personal Web space, i.e. under http;//my.server.com/~username

**Comment by WardCunningham** [comment]
The design goal was to allow pages to move freely between owners. If each site owner were to design their own routing scheme then every client would need to know or learn every routing scheme in use. This is not a problem where server addressing and internal routing are bound together in a single string, the url. We break that convention and thus open up a new landscape for innovation.

**Comment by WardCunningham** [comment]
I should add that I am familiar with the hurdles that corporate network administrators create while thinking that they are serving their organization's needs. I once spent two months just getting one organization to reconfigure their nanny-proxy to allow employees to visit federated wiki sites on the public internet. In the end they would permit them only one by one by ip address.

I encourage you to experiment. If you discover an approach we haven't considered, please let us know. We collect tips at http://admin.asia.wiki.org/

**Comment by khinsen** [comment]
@WardCunningham Again I sympathize with everything you say. But the world we live in is not the world we are dreaming of. And life is short, so we can't work on fixing all problems. I have chosen a different aspect of the world to work on (making computational science more reliable), and I look at new technology very egoistically from that point of view: will it help me to achieve my goals?

My impression (after watching a few video presentations and using wiki locally on my computer) is that this could be very useful technology for scientists, in that it enables collective reflection. But if scientists first have to reform their organizations before they can even try out this technology, then it's probably not going to happen. Of course, I would like to be proven wrong!

As for different approaches, I must confess that I don't even understand where the problem is. From my perhaps naive point of view, a wiki could be identified by a more general URL prefix of the form http://my.server.com/my-wiki/, with all internal access paths relative to this root URL. I do realize that this would be more work to implement in the server, but it shouldn't make a big difference for the clients.

**Comment by WardCunningham** [comment]
It remains my belief that you would be happier throughout your career if you separated your most important work from the administrative policies of your current university, especially if those policies obstruct open digital science. I recognize that there is an issue of brand here and probably intellectual property ownership issues too. However, I refuse to believe that registering a domain name and setting up a paas server is any harder than installing and operating any other piece of scientific equipment.

I will leave you with two tips and consider this issue closed.

http://forage.ward.fed.wiki.org/view/deploying-a-wiki
http://admin.asia.wiki.org/view/maintaining-a-custom-wiki
