### ISSUE TITLE
Installation problems on Debian Jessie

### ISSUE THREAD

**Issue by i2p-lbt** [fedwiki/wiki#61]
I tried to install on Debian Jessie with 
```
root@host:~# apt-get install npm
[...]
root@host:~# npm install -g wiki
[...]
root@host:~# wiki
/usr/bin/env: node: No such file or directory
```
During installation several warnings were issued. Mostly because of optional dependencies, but also
```
/bin/sh: 1: node: not found
gyp: Call to 'node -e "require('nan')"' returned exit status 127. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:344:16)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:809:12)
gyp ERR! System Linux 3.16.0-4-amd64
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/wiki/node_modules/wiki-plugin-linkmap/node_modules/ws/node_modules/utf-8-validate
gyp ERR! node -v v0.10.29
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
```
Looking into the referenced file I found `Scripts calling Node.js as a shell command must be changed to instead use the "nodejs" command.`. Now I'm trying to find out what I do need to change to get this to run, but my searching was unsuccessful so far. I did search the net and the issues, but that didn't help me. Help appreciated.

**Comment by almereyda** [comment]
What do `node -v` and `which node` return on your shell?

**Comment by i2p-lbt** [comment]
Nothing, like in command not found. As in the quoted text, I have to issue `nodejs -v` and then it says `v0.10.29`. I just found if I edit `/usr/local/lib/node_modules/wiki/index.js` and make the first line a `#!/usr/bin/env nodejs`, then the server comes up. And I don't know about nvm (I'm new to this node-stuff actually).

This should be documented somewhere, though. I assume it already is, but only found the wiki-pages of the original repo of Ward so far. No idea if you could modify the code to autodetect this on Debian. I'll leave this open for now until I found out how to address the documenation - or where it hides ;)

**Comment by almereyda** [comment]
This is a known weirdness of the Debian packaging for the `nodejs` package.
You can work around globally by creating a symlink.

    sudo ln -s /usr/bin/nodejs /usr/bin/node

Source: https://github.com/nodejs/node-v0.x-archive/wiki/Installing-Node.js-via-package-manager
Official installation instructions for Node.js can be found at https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions and also mention this behaviour:

> A Node.js package is also available in the [official repo](http://packages.debian.org/search?searchon=names&keywords=nodejs) for Debian Sid (unstable), Jessie (testing) and Wheezy (wheezy-backports) as "nodejs". It only installs a `nodejs` binary, so you might want to `ln -s /usr/bin/nodejs /usr/bin/node` for many things to work.

Can you confirm we can close this issue?

**Comment by i2p-lbt** [comment]
Thx 4 pointing that out and sorry for not finding it myself - was stuck on searching in conjunction with "fedwiki" I guess. And yes, although I got the feeling there might be other users running into this trap. May I suggest to adding an according hint to the readme.md? I'd draft one if you want ...

**Comment by almereyda** [comment]
Hmm. I don't see as a specific wiki isuue, as all npm modules which offer a
CLI would kind of need this addition. Maybe there is a place with an
overview of Node.js installation options? (Self-compilation, Package
Managers, nvm, etc.)

**Comment by i2p-lbt** [comment]
Sure, it's not "your problem" or anything. But any people attempting to install under a Debian-based system and without knowledge about node.js will run into this problem. I didn't find it straight-forward to find the solution, it did cost me time. Reading error-output, hacking it to work, finding out about the general work-around (thx to you). It would just have been a few lines in your readme.md to point this out and make it easier for those affected. But no problem if you do not want that, I just thought this might be a little improvement worth including ... Closing this then. Sorry if I wasted your time. And thank you again for your help.

**Comment by almereyda** [comment]
No, you didn't waste our time at all. Unfortunately I am not a maintainer
of this project and will not make any design decisions on how the
documentation should look like. Should we probably introduce a seperate
README for different deployment options? There's already NPM, different
distributions, Docker, PaaS and several other deployment options available.
We could use this thread to sketch a Deployment.md together, if you are
interested.

**Comment by i2p-lbt** [comment]
Well, I can't make those "decisions" either I guess? You asked for this to be closed, so I did that. I had drafted something into my cloned readme.md already. In case there is interest to include this somewhere, I am more than willing to draft something again (as I deleted that other change already). Here we go:

> Note on Debian: the Debian node.js package uses a different naming (i.e. nodejs instead of node.js). You will either need to adapt the wiki-sources or do `ln -s /usr/bin/nodejs /usr/bin/node` as a general workaround. Both might have implications on maintainance. See `/usr/share/doc/nodejs/README.Debian` for more information.

Feel free to add this anywhere you think it's appropriate, I still feel it might lower the start-up difficulties for some users quite some. This information is contained in the output during installation. However, in my case there were quite some optional dependencies producing warnings, so it was a "searching in the scroll" and fairly easy to overlook.

**Comment by WardCunningham** [comment]
@i2p-lbt welcome to federated wiki.
@almereyda thank you for your assistance with this issue.

We once tried to maintain a github wiki with install advice but it was never very complete and fell into disuse as we separated our repositories from my personal account.

I hope someday to see platform based self-help communities offering all kinds of advice by writing in federated wiki itself. An embryonic version of this exists with a slant toward digital ocean.
http://admin.asia.wiki.org/

**Comment by i2p-lbt** [comment]
Thx 4 the welcome and thx 4 the link. Very interesting content there that I wasn't able to find yesterday while trying to follow all (?) links from fed.wiki.org. I found it hard to find documentation, especially technical. Maybe consider composing an overview with important starting points for reading and pointing to that very clearly? For example including a hint to admin.asia and your suggestion how to document there? Although that domain sounds ... asia-specific, I first expected to find Mandarin there ;) My problems might be due to the disabled js though. It seems admin.asia is more friendly on non-js than fed.wiki.org btw. ...
