### ISSUE TITLE
Provide list of / links to special client pages

### ISSUE THREAD

**Issue by i2p-lbt** [fedwiki/wiki#67]
I do not understand the underlying concepts of the js-client-architecture, but realised that one thing that was confusing to me were the *special pages* (what's your taxonomy here?) like `/recent-changes.html`. For my perception these present a client-functionality which I then would expect to be available in the client. At the current I had to meet a link to such a page on some server to actually get to know about/use it. Could be easily addressed though, I guess. For example by placing icons/buttons in the bottom line on the right. At least for me the browser page usually has a width that leaves 1/3 to 1/4 of that bottom line on the right empty. On the other hand a more distinct separation from the login, which rather seems server-side to me, might be desirable.

If you don't want that for some reason, providing a list of all special pages available at a prominent place so that any user has to notice them might be an alternative?

**Comment by WardCunningham** [comment]
The welcome page has special status. Others just come from various places that are under a sites control. There is a list of buttons in the web page footer that will bring up the welcome page for each site in the neighborhood. By convention this page will have links to useful pages like How to Wiki and Recent Changes. Of course site owners are free to disregard the convention no matter how misguided that might be.
