### ISSUE TITLE
URLs sometimes don't work directly

### ISSUE THREAD

**Issue by genjiamin** [fedwiki/wiki#77]
Copying URLs from the URL bar in the browser and entering the website directly doesn't always work.

In some of the cases it directs to 'Welcome visitors'. Clicking the back button in the browser then leads to the desired page. Here's two examples of this:
http://idiom.sfw.c2.com/view/welcome-visitors/view/idiom-or-pattern
http://pattern.sfw.c2.com/view/welcome-visitors/view/search-results/view/pattern-backlash

I am using Mozilla Firefox 45.0 on Ubuntu LTS 14.04.

**Comment by WardCunningham** [comment]
That site is served by a perl script. It hides this pretty well but doesn't do all the same startup code.

**Comment by WardCunningham** [comment]
The perl script is available here. Issues welcome.
https://github.com/WardCunningham/c2-sfw-script

**Comment by genjiamin** [comment]
Alright. Shall I open this issue over there?

**Comment by WardCunningham** [comment]
Yes. You can just link there to the discussion here. You posting will register you for updates should that limitation ever be addressed.

We've explored many ways of importing information into federated wiki. The c2-sfw-script was written by editing the original c2-wiki cgi script. This was both easy and now informs our current and more promising notion of transporters and especially transport proxies. 

http://ward.asia.wiki.org/transporting-hypertext.html
http://ward.asia.wiki.org/explore-transport-proxy.html
