### ISSUE TITLE
Wiki@Next

### ISSUE THREAD

**Issue by paul90** [fedwiki/wiki#78]
This issue is for tracking issues with wiki@next

- [x] [claim not getting reflecting in server state](https://github.com/fedwiki/wiki-server/issues/119) - fixed in wiki-security-passportjs@0.1.0-2
- [x] the authentication check is failing - fedwiki/wiki-security-passportjs#1

**To Do:**

- [x] document changes to configuration
- [x] add support for adding alternative identities

**Comment by almereyda** [comment]
The notation of the issue title suggest to imply the existence of a branch called [fedwiki/wiki@`next`](https://github.com/fedwiki/wiki/tree/next).

**Comment by paul90** [comment]
There is a next branch - it is mainly about switching away from Mozilla Persona that is closing later this year.
